In [1]:
import random

class BankAccount:
    def __init__(self, account_id, balance=0):
        self.account_id = account_id
        self.balance = balance
        self.transactions = []

    def deposit(self, amount):
        self.balance += amount
        self.transactions.append(('deposit', amount))

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            self.transactions.append(('withdrawal', amount))
        else:
            
            self.transactions.append(('failed withdrawal', amount))

    def __repr__(self):
        return f"Account ID: {self.account_id}, Balance: {self.balance:.2f}"


def generate_accounts(num_accounts=100, seed=1000, months=6, max_transactions_per_month=10):
    random.seed(seed)
    accounts = []
    
    for account_id in range(1, num_accounts + 1):
        initial_balance = round(random.uniform(100, 10000), 2)
        account = BankAccount(account_id, initial_balance)
        
        for _ in range(months):
            
            for _ in range(random.randint(1, max_transactions_per_month)):
                transaction_type = random.choice(['deposit', 'withdrawal'])
                amount = round(random.uniform(50, 2000), 2)
                
                if transaction_type == 'deposit':
                    account.deposit(amount)
                elif transaction_type == 'withdrawal':
                    account.withdraw(amount)

        accounts.append(account)

    
    accounts.sort(key=lambda acc: acc.balance)
    return accounts


accounts = generate_accounts()

accounts

[Account ID: 7, Balance: 54.72,
 Account ID: 53, Balance: 67.02,
 Account ID: 82, Balance: 162.67,
 Account ID: 31, Balance: 209.34,
 Account ID: 46, Balance: 232.73,
 Account ID: 3, Balance: 263.18,
 Account ID: 76, Balance: 319.32,
 Account ID: 99, Balance: 338.98,
 Account ID: 72, Balance: 364.49,
 Account ID: 97, Balance: 693.36,
 Account ID: 43, Balance: 1040.09,
 Account ID: 95, Balance: 1298.26,
 Account ID: 61, Balance: 1354.38,
 Account ID: 12, Balance: 1378.04,
 Account ID: 30, Balance: 1389.60,
 Account ID: 70, Balance: 1434.89,
 Account ID: 68, Balance: 1705.08,
 Account ID: 67, Balance: 1768.19,
 Account ID: 89, Balance: 1878.99,
 Account ID: 83, Balance: 2076.08,
 Account ID: 19, Balance: 2098.67,
 Account ID: 81, Balance: 2140.22,
 Account ID: 96, Balance: 2153.20,
 Account ID: 8, Balance: 2153.60,
 Account ID: 93, Balance: 2233.49,
 Account ID: 1, Balance: 2338.97,
 Account ID: 26, Balance: 2556.34,
 Account ID: 69, Balance: 2653.35,
 Account ID: 59, Balance: 2695.99,
 Account ID: 39, Balance: 2755.49,
 Account ID: 48, Balance: 2773.28,
 Account ID: 60, Balance: 3152.44,
 Account ID: 42, Balance: 3155.09,
 Account ID: 65, Balance: 3356.12,
 Account ID: 55, Balance: 3403.01,
 Account ID: 37, Balance: 3501.29,
 Account ID: 86, Balance: 3666.35,
 Account ID: 85, Balance: 4030.46,
 Account ID: 75, Balance: 4168.44,
 Account ID: 73, Balance: 4237.31,
 Account ID: 49, Balance: 4283.56,
 Account ID: 47, Balance: 4805.35,
 Account ID: 15, Balance: 4816.50,
 Account ID: 20, Balance: 4877.10,
 Account ID: 14, Balance: 4933.51,
 Account ID: 35, Balance: 5082.10,
 Account ID: 38, Balance: 5183.24,
 Account ID: 71, Balance: 5195.39,
 Account ID: 77, Balance: 5509.27,
 Account ID: 9, Balance: 5650.76,
 Account ID: 62, Balance: 6229.85,
 Account ID: 64, Balance: 6274.56,
 Account ID: 92, Balance: 6339.94,
 Account ID: 74, Balance: 6480.02,
 Account ID: 18, Balance: 6495.63,
 Account ID: 88, Balance: 6722.38,
 Account ID: 33, Balance: 6813.34,
 Account ID: 6, Balance: 6904.84,
 Account ID: 4, Balance: 6935.29,
 Account ID: 87, Balance: 7024.37,
 Account ID: 52, Balance: 7324.98,
 Account ID: 57, Balance: 7635.68,
 Account ID: 91, Balance: 7736.35,
 Account ID: 44, Balance: 7912.94,
 Account ID: 17, Balance: 8032.64,
 Account ID: 5, Balance: 8308.02,
 Account ID: 13, Balance: 8550.32,
 Account ID: 21, Balance: 8676.42,
 Account ID: 94, Balance: 8792.98,
 Account ID: 2, Balance: 9047.44,
 Account ID: 16, Balance: 9132.34,
 Account ID: 34, Balance: 9183.96,
 Account ID: 32, Balance: 9348.71,
 Account ID: 36, Balance: 9348.90,
 Account ID: 51, Balance: 9469.13,
 Account ID: 79, Balance: 9870.70,
 Account ID: 80, Balance: 9870.94,
 Account ID: 84, Balance: 10262.79,
 Account ID: 63, Balance: 10321.28,
 Account ID: 29, Balance: 11417.19,
 Account ID: 23, Balance: 11494.63,
 Account ID: 11, Balance: 11634.45,
 Account ID: 66, Balance: 11899.87,
 Account ID: 40, Balance: 12206.73,
 Account ID: 25, Balance: 13123.10,
 Account ID: 56, Balance: 13547.38,
 Account ID: 10, Balance: 13788.33,
 Account ID: 41, Balance: 14084.92,
 Account ID: 54, Balance: 14164.88,
 Account ID: 28, Balance: 14341.19,
 Account ID: 45, Balance: 14478.04,
 Account ID: 58, Balance: 14687.07,
 Account ID: 78, Balance: 15052.57,
 Account ID: 22, Balance: 15086.71,
 Account ID: 24, Balance: 15581.55,
 Account ID: 27, Balance: 16156.28,
 Account ID: 100, Balance: 16503.82,
 Account ID: 98, Balance: 17914.62,
 Account ID: 90, Balance: 19619.90,
 Account ID: 50, Balance: 22673.54]